export const BONG_HITS_DATABASE_NAME: string = "BongHits";
export const STRAINS_DATABASE_NAME: string = "Strains";

export const dayLookUpTable = new Map<number, string>()
dayLookUpTable.set(0, "Sun");
dayLookUpTable.set(1, "Mon");
dayLookUpTable.set(2, "Tue");
dayLookUpTable.set(3, "Wed");
dayLookUpTable.set(4, "Thu");
dayLookUpTable.set(5, "Fri");
dayLookUpTable.set(6, "Sat");

// Function to generate strain insert statements
export function getStrainInsertStatements(): string {
  return '';  // Empty implementation for now
}

export const COLORS = {
  background: '#000000',
  cardBackground: '#1A1A1A',
  primary: '#00E676',       // Neon green 
  primaryLight: '#69F0AE',  // Light neon green
  primaryDark: '#00C853',   // Darker green
  text: {
    primary: '#FFFFFF',
    secondary: '#FFFFFFCC',  // 80% white
    tertiary: '#FFFFFF99',   // 60% white
  },
  chart: {
    primary: '#00E676',
    secondary: '#69F0AE',
    background: '#1A1A1A',
  },
  gradientColors: {
    start: 'rgba(0,230,118,0.4)',
    middle: 'rgba(105,240,174,0.2)',
    end: 'rgba(0,0,0,0)',
  }
};


export const SAMPLE_STRAINS = [
  {
    name: "Trainwreck",
    overview: "Sativa-dominant hybrid known for its explosive cerebral high and rapid onset.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Mexican, Thai, Afghani",
    thc_range: "18-22%",
    cbd_level: "Minimal",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Spicy, citrus aroma with a hint of pine; dense, energetic buds",
    effects: "Energized, Creative, Uplifted",
    negatives: "dry mouth, dry eyes, dizziness",
    uses: "Ideal for creative pursuits, social settings, combating fatigue",
    thc_rating: 7.5,
    user_rating: 7.0,
    combined_rating: 7.25
  },
  {
    name: "Blue Dream",
    overview: "Balanced sativa-dominant hybrid offering gentle cerebral invigoration and full-body relaxation.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Blueberry x Haze",
    thc_range: "17-24%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene, Caryophyllene",
    qualitative_insights: "Sweet berry aroma with earthy undertones; smooth buds",
    effects: "Euphoric, Relaxed, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Great for stress relief, daytime use, creative tasks",
    thc_rating: 7.75,
    user_rating: 7.5,
    combined_rating: 7.63
  },
  {
    name: "Girl Scout Cookies",
    overview: "Popular hybrid known for its euphoric and relaxing effects with a sweet, earthy aroma.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "OG Kush x Durban Poison",
    thc_range: "18-28%",
    cbd_level: "Low",
    dominant_terpenes: "Caryophyllene, Limonene",
    qualitative_insights: "Sweet, earthy scent with hints of mint; dense, resinous buds",
    effects: "Happy, Relaxed, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Effective for pain relief and mood elevation",
    thc_rating: 9,
    user_rating: 8.5,
    combined_rating: 8.75
  },
  {
    name: "Sour Diesel",
    overview: "Energetic sativa-dominant strain with a pungent diesel aroma.",
    genetic_type: "Sativa-dominant",
    lineage: "Chemdawg x Super Skunk",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Pungent, fuel-like scent with citrus hints; airy buds",
    effects: "Energetic, Uplifted, Focused",
    negatives: "dry mouth, anxiety",
    uses: "Ideal for daytime use and creative projects",
    thc_rating: 8.75,
    user_rating: 8,
    combined_rating: 8.38
  },
  {
    name: "OG Kush",
    overview: "Iconic hybrid delivering a balanced high with earthy pine and citrus flavors.",
    genetic_type: "Hybrid",
    lineage: "Chemdawg x Hindu Kush",
    thc_range: "19-26%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Earthy, pine aroma with a touch of citrus; dense, resinous buds",
    effects: "Relaxed, Euphoric, Uplifted",
    negatives: "dry mouth, dry eyes",
    uses: "Used for stress relief and pain management",
    thc_rating: 8.75,
    user_rating: 8,
    combined_rating: 8.38
  },
  {
    name: "Pineapple Express",
    overview: "Tropical sativa-dominant hybrid offering a sweet, fruity flavor and energetic high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Trainwreck x Hawaiian",
    thc_range: "19-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Tropical pineapple aroma with hints of earthiness; vibrant buds",
    effects: "Energetic, Uplifted, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Perfect for social settings and daytime activities",
    thc_rating: 8.5,
    user_rating: 8,
    combined_rating: 8.25
  },
  {
    name: "Granddaddy Purple",
    overview: "Renowned indica-dominant strain with a deep purple hue and grape-like aroma.",
    genetic_type: "Indica-dominant",
    lineage: "Purple Urkle x Big Bud",
    thc_range: "17-23%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Sweet, grape aroma with a relaxing, heavy bud structure",
    effects: "Relaxed, Sleepy, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for pain relief and insomnia",
    thc_rating: 7.5,
    user_rating: 7,
    combined_rating: 7.25
  },
  {
    name: "White Widow",
    overview: "Balanced hybrid known for its potent resin production and earthy pine flavor.",
    genetic_type: "Hybrid",
    lineage: "Brazilian Sativa x South Indian Indica",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, woody aroma with a subtle sweet note; frosty buds",
    effects: "Energetic, Euphoric, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Suitable for stress relief and social use",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "AK-47",
    overview: "Sativa-dominant hybrid offering a mellow, long-lasting cerebral high with a sweet, sour flavor.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Colombian, Mexican, Thai, Afghani",
    thc_range: "13-20%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Sweet and sour aroma with a light, airy bud structure",
    effects: "Relaxed, Uplifted, Creative",
    negatives: "dry mouth, fatigue",
    uses: "Great for relaxation and creative inspiration",
    thc_rating: 5.75,
    user_rating: 6,
    combined_rating: 5.88
  },
  {
    name: "Durban Poison",
    overview: "Pure sativa known for its energizing effects and sweet, earthy aroma.",
    genetic_type: "Pure Sativa",
    lineage: "South African Landrace",
    thc_range: "15-25%",
    cbd_level: "Low",
    dominant_terpenes: "Terpinolene, Myrcene",
    qualitative_insights: "Sweet, earthy scent with hints of pine; light, fluffy buds",
    effects: "Energizing, Uplifting, Focused",
    negatives: "dry mouth, insomnia",
    uses: "Ideal for daytime use and outdoor activities",
    thc_rating: 7.5,
    user_rating: 7,
    combined_rating: 7.25
  },
  {
    name: "Purple Haze",
    overview: "Sativa-dominant strain with a distinctive purple hue and uplifting high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Haze lineage",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Fruity, berry aroma with a hint of spice; colorful buds",
    effects: "Uplifted, Creative, Euphoric",
    negatives: "dry mouth, dry eyes",
    uses: "Suitable for creative endeavors and social gatherings",
    thc_rating: 6.25,
    user_rating: 6.5,
    combined_rating: 6.38
  },
  {
    name: "Green Crack",
    overview: "Intense sativa-dominant strain known for its energizing and focused high.",
    genetic_type: "Sativa-dominant",
    lineage: "Afghani x Skunk #1",
    thc_range: "15-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Citrus and tropical fruit aroma; tight, potent buds",
    effects: "Energetic, Focused, Uplifted",
    negatives: "dry mouth, anxiety",
    uses: "Perfect for daytime energy and focus",
    thc_rating: 7.5,
    user_rating: 7.25,
    combined_rating: 7.38
  },
  {
    name: "Jack Herer",
    overview: "Award-winning sativa-dominant hybrid celebrated for its clear-headed and creative high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Haze x Northern Lights x Shiva Skunk",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Terpinolene, Caryophyllene",
    qualitative_insights: "Spicy, pine aroma with hints of citrus; frosty buds",
    effects: "Uplifted, Creative, Euphoric",
    negatives: "dry mouth, paranoia",
    uses: "Ideal for creative tasks and stress relief",
    thc_rating: 8,
    user_rating: 8,
    combined_rating: 8.00
  },
  {
    name: "Chemdawg",
    overview: "Potent hybrid with a strong diesel aroma and robust cerebral high.",
    genetic_type: "Hybrid",
    lineage: "Likely Chemdawg #4 x Unknown",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Pungent diesel scent with a hint of spice; dense buds",
    effects: "Focused, Euphoric, Relaxed",
    negatives: "dry mouth, dry eyes",
    uses: "Used for mood enhancement and pain relief",
    thc_rating: 6.25,
    user_rating: 6.5,
    combined_rating: 6.38
  },
  {
    name: "Lemon Haze",
    overview: "Sativa-dominant hybrid with a zesty lemon flavor and invigorating high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Lemon Skunk x Silver Haze",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Bright citrus aroma with a sweet undertone; light, airy buds",
    effects: "Energized, Uplifted, Happy",
    negatives: "dry mouth, anxiety",
    uses: "Great for daytime use and creative activities",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Northern Lights",
    overview: "Classic indica-dominant strain known for its deeply relaxing and sedative effects.",
    genetic_type: "Indica-dominant",
    lineage: "Afghani x Thai",
    thc_range: "16-21%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Sweet and spicy aroma with resinous, compact buds",
    effects: "Relaxed, Sleepy, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for pain relief and insomnia",
    thc_rating: 6.75,
    user_rating: 6.25,
    combined_rating: 6.50
  },
  {
    name: "Critical Mass",
    overview: "Indica-dominant strain famous for its heavy yields and potent body high.",
    genetic_type: "Indica-dominant",
    lineage: "Afghani x Skunk #1",
    thc_range: "19-21%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy and sweet aroma; large, dense buds",
    effects: "Relaxed, Sedated, Happy",
    negatives: "dry mouth, couch-lock",
    uses: "Suitable for chronic pain and stress relief",
    thc_rating: 7.5,
    user_rating: 7,
    combined_rating: 7.25
  },
  {
    name: "Bubble Gum",
    overview: "Balanced hybrid with a sweet, bubble gum flavor and uplifting effects.",
    genetic_type: "Hybrid",
    lineage: "Unknown (landrace blend)",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Caryophyllene, Limonene",
    qualitative_insights: "Sweet, fruity aroma reminiscent of bubble gum; soft buds",
    effects: "Happy, Euphoric, Relaxed",
    negatives: "dry mouth, dizziness",
    uses: "Good for mood elevation and mild pain relief",
    thc_rating: 6.25,
    user_rating: 6,
    combined_rating: 6.13
  },
  {
    name: "Amnesia Haze",
    overview: "Sativa-dominant hybrid known for its potent, uplifting high and complex flavor profile.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Haze lineage",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Terpinolene, Myrcene",
    qualitative_insights: "Earthy and citrus aroma with a hint of spice; airy buds",
    effects: "Uplifted, Creative, Euphoric",
    negatives: "dry mouth, paranoia",
    uses: "Ideal for creative tasks and social settings",
    thc_rating: 8.75,
    user_rating: 8.25,
    combined_rating: 8.50
  },
  {
    name: "Strawberry Cough",
    overview: "Sativa-dominant strain celebrated for its sweet strawberry aroma and smooth, uplifting high.",
    genetic_type: "Sativa-dominant",
    lineage: "Possibly Haze-based",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Sweet berry scent with a subtle herbal note; light buds",
    effects: "Uplifted, Euphoric, Focused",
    negatives: "dry mouth, coughing",
    uses: "Great for stress relief and creative pursuits",
    thc_rating: 6.25,
    user_rating: 6,
    combined_rating: 6.13
  },
  {
    name: "Maui Wowie",
    overview: "Tropical sativa-dominant strain delivering an energetic high with a fruity, exotic flavor.",
    genetic_type: "Sativa-dominant",
    lineage: "Hawaiian Landrace",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Tropical pineapple and citrus aroma; light, airy buds",
    effects: "Energizing, Uplifted, Creative",
    negatives: "dry mouth, dizziness",
    uses: "Perfect for daytime energy and relaxation",
    thc_rating: 6.25,
    user_rating: 6.5,
    combined_rating: 6.38
  },
  {
    name: "Grape Ape",
    overview: "Indica-dominant strain known for its distinct grape aroma and deeply relaxing effects.",
    genetic_type: "Indica-dominant",
    lineage: "Afghani x Mendocino Purps",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Sweet, grape-like aroma; colorful, dense buds",
    effects: "Relaxed, Sedated, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and pain management",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Blueberry",
    overview: "Indica-dominant strain with a renowned blueberry aroma and soothing effects.",
    genetic_type: "Indica-dominant",
    lineage: "Blueberry x Afghan",
    thc_range: "16-24%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Sweet blueberry scent with earthy undertones; frosty buds",
    effects: "Relaxed, Euphoric, Sleepy",
    negatives: "dry mouth, drowsiness",
    uses: "Used for relaxation and mild pain relief",
    thc_rating: 7.5,
    user_rating: 7,
    combined_rating: 7.25
  },
  {
    name: "Cherry Pie",
    overview: "Hybrid strain offering a sweet and tart cherry flavor with balanced effects.",
    genetic_type: "Hybrid",
    lineage: "Granddaddy Purple x Durban Poison",
    thc_range: "16-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet, tart cherry aroma; sticky, dense buds",
    effects: "Happy, Relaxed, Euphoric",
    negatives: "dry mouth, dry eyes",
    uses: "Suitable for mood elevation and pain relief",
    thc_rating: 7,
    user_rating: 7,
    combined_rating: 7.00
  },
  {
    name: "Super Silver Haze",
    overview: "Sativa-dominant hybrid with a potent, energetic high and complex citrus-spice profile.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Skunk, Northern Lights, Haze",
    thc_range: "18-23%",
    cbd_level: "Low",
    dominant_terpenes: "Terpinolene, Myrcene",
    qualitative_insights: "Citrus and earthy aroma with spicy notes; frosty buds",
    effects: "Energized, Uplifted, Focused",
    negatives: "dry mouth, anxiety",
    uses: "Ideal for daytime creativity and stress relief",
    thc_rating: 7.75,
    user_rating: 7.5,
    combined_rating: 7.63
  },
  {
    name: "Bruce Banner",
    overview: "Potent hybrid known for its explosive high and pungent, sweet diesel aroma.",
    genetic_type: "Hybrid",
    lineage: "OG Kush x Strawberry Diesel",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Sweet, diesel-like aroma with a hint of fruit; dense buds",
    effects: "Euphoric, Energetic, Creative",
    negatives: "dry mouth, paranoia",
    uses: "Used for mood enhancement and pain management",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Wedding Cake",
    overview: "Indica-dominant hybrid with a rich, tangy flavor and a potent, relaxing high.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Cherry Pie x Girl Scout Cookies",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Caryophyllene, Limonene",
    qualitative_insights: "Sweet, earthy aroma with a hint of vanilla; dense buds",
    effects: "Relaxed, Happy, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and pain management",
    thc_rating: 8.75,
    user_rating: 8.25,
    combined_rating: 8.50
  },
  {
    name: "Gelato",
    overview: "Balanced hybrid celebrated for its dessert-like flavor and euphoric, calming effects.",
    genetic_type: "Hybrid",
    lineage: "Sunset Sherbet x Thin Mint GSC",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet, creamy aroma with hints of citrus; sticky buds",
    effects: "Relaxed, Happy, Uplifted",
    negatives: "dry mouth, dizziness",
    uses: "Great for relaxation and mood enhancement",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Sunset Sherbet",
    overview: "Indica-dominant hybrid known for its fruity dessert flavor and soothing high.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Girl Scout Cookies x Pink Panties",
    thc_range: "18-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Fruity, sherbet-like aroma; vibrant, dense buds",
    effects: "Relaxed, Euphoric, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Suitable for evening relaxation and stress relief",
    thc_rating: 7.5,
    user_rating: 7,
    combined_rating: 7.25
  },
  {
    name: "GMO (Garlic Cookies)",
    overview: "Indica-dominant hybrid with a pungent garlic aroma and deeply relaxing effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Chemdawg x GSC",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Caryophyllene, Myrcene",
    qualitative_insights: "Pungent, savory aroma with earthy undertones; sticky buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for pain relief and stress reduction",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Do-Si-Dos",
    overview: "Indica-dominant hybrid offering a sweet and earthy flavor with potent relaxing effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Girl Scout Cookies x Face Off OG",
    thc_range: "18-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet, floral aroma with hints of mint; dense, resinous buds",
    effects: "Relaxed, Euphoric, Sedated",
    negatives: "dry mouth, drowsiness",
    uses: "Used for anxiety relief and relaxation",
    thc_rating: 7.5,
    user_rating: 7,
    combined_rating: 7.25
  },
  {
    name: "Runtz",
    overview: "Balanced hybrid known for its sweet, candy-like flavor and powerful, euphoric high.",
    genetic_type: "Hybrid",
    lineage: "Zkittlez x Gelato",
    thc_range: "19-29%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Fruity, candy-like aroma; vibrant, colorful buds",
    effects: "Happy, Euphoric, Relaxed",
    negatives: "dry mouth, dizziness",
    uses: "Ideal for creative pursuits and mood enhancement",
    thc_rating: 9.5,
    user_rating: 9,
    combined_rating: 9.25
  },
  {
    name: "Zkittlez",
    overview: "Indica-dominant hybrid with a sweet, fruity flavor and a relaxing, mellow high.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Grape Ape x Grapefruit",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Intensely sweet, fruity aroma; compact, resinous buds",
    effects: "Relaxed, Happy, Euphoric",
    negatives: "dry mouth, dry eyes",
    uses: "Great for stress relief and relaxation",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Biscotti",
    overview: "Hybrid strain offering a rich, cookie-like flavor paired with a balanced high.",
    genetic_type: "Hybrid",
    lineage: "Girl Scout Cookies x South Florida OG",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet, baked aroma with hints of spice; dense, trichome-rich buds",
    effects: "Happy, Relaxed, Uplifted",
    negatives: "dry mouth, drowsiness",
    uses: "Suitable for creative tasks and relaxation",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Tahoe OG",
    overview: "Indica-dominant strain with a robust, earthy pine flavor and potent body effects.",
    genetic_type: "Indica-dominant",
    lineage: "OG Kush lineage",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Earthy, pine aroma with a hint of spice; compact, sticky buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, couch-lock",
    uses: "Ideal for pain relief and stress management",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Forbidden Fruit",
    overview: "Hybrid strain known for its tropical, fruity flavor and deeply relaxing high.",
    genetic_type: "Hybrid",
    lineage: "Tangie x Cherry Pie",
    thc_range: "18-23%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Tropical, citrusy aroma with sweet undertones; resinous buds",
    effects: "Relaxed, Happy, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Great for evening relaxation and mood enhancement",
    thc_rating: 7.75,
    user_rating: 7.5,
    combined_rating: 7.63
  },
  {
    name: "Agent Orange",
    overview: "Sativa-dominant hybrid offering a zesty citrus flavor and uplifting effects.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Orange Velvet x Jack the Ripper",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Vibrant citrus aroma with sweet, tangy notes; frosty buds",
    effects: "Energized, Uplifted, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for daytime use and creative inspiration",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Sour Tangie",
    overview: "Sativa-dominant hybrid blending sour diesel with tangy citrus flavors for a vibrant high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Sour Diesel x Tangie",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Tangy citrus aroma with a hint of sour diesel; dense buds",
    effects: "Energized, Uplifted, Focused",
    negatives: "dry mouth, anxiety",
    uses: "Suitable for creative projects and daytime activities",
    thc_rating: 8,
    user_rating: 7.75,
    combined_rating: 7.88
  },
  {
    name: "Critical Kush",
    overview: "Indica-dominant hybrid merging heavy yields with a potent, relaxing high.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Critical Mass x OG Kush",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, pine aroma with subtle sweetness; chunky buds",
    effects: "Relaxed, Sedated, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Great for pain relief and evening relaxation",
    thc_rating: 8.75,
    user_rating: 8.25,
    combined_rating: 8.50
  },
  {
    name: "Alaskan Thunder Fuck",
    overview: "Sativa-dominant hybrid known for its strong, uplifting high and pungent, piney aroma.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Afghani x Unknown",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Pinene, Myrcene",
    qualitative_insights: "Pungent, piney scent with earthy undertones; frosty, energizing buds",
    effects: "Energized, Uplifted, Creative",
    negatives: "dry mouth, anxiety",
    uses: "Ideal for boosting energy and focus",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Harlequin",
    overview: "CBD-rich sativa-dominant strain celebrated for its clear-headed, medicinal effects.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Colombian Gold x Nepalese",
    thc_range: "7-15%",
    cbd_level: "High",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Earthy, herbal aroma with subtle sweetness; lighter buds",
    effects: "Clear-headed, Relaxed, Focused",
    negatives: "dry mouth, dizziness",
    uses: "Used for pain relief and anxiety management",
    thc_rating: 3,
    user_rating: 3.5,
    combined_rating: 3.25
  },
  {
    name: "Cannatonic",
    overview: "Balanced hybrid renowned for its low THC and high CBD content, offering gentle relief.",
    genetic_type: "Hybrid",
    lineage: "MK Ultra x G13",
    thc_range: "6-17%",
    cbd_level: "High",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Earthy and citrus aroma; soft, resinous buds",
    effects: "Calm, Relaxed, Focused",
    negatives: "dry mouth, fatigue",
    uses: "Ideal for medical use and anxiety relief",
    thc_rating: 3.25,
    user_rating: 3.5,
    combined_rating: 3.38
  },
  {
    name: "Charlotte's Web",
    overview: "CBD-dominant strain with minimal psychoactive effects, designed for therapeutic use.",
    genetic_type: "CBD-dominant",
    lineage: "High CBD phenotype of hemp",
    thc_range: "0-0.3%",
    cbd_level: "Very High",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Mild, herbal aroma; less resinous buds",
    effects: "Calm, Focused, Clear-headed",
    negatives: "none",
    uses: "Used for epilepsy and chronic pain management",
    thc_rating: 0.5,
    user_rating: 0.5,
    combined_rating: 0.5
  },
  {
    name: "Remedy",
    overview: "Balanced hybrid with high CBD content offering mild relaxation without strong psychoactive effects.",
    genetic_type: "Hybrid",
    lineage: "CBD-rich phenotype",
    thc_range: "1-4%",
    cbd_level: "High",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Earthy, citrus notes; soft buds",
    effects: "Relaxed, Clear-headed, Calm",
    negatives: "dry mouth, sedation",
    uses: "Ideal for anxiety and pain relief",
    thc_rating: 3.5,
    user_rating: 3.75,
    combined_rating: 3.63
  },
  {
    name: "Pennywise",
    overview: "Indica-dominant strain with a near 1:1 THC to CBD ratio, offering balanced effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Harle-Tsu x Jack the Ripper",
    thc_range: "4-8%",
    cbd_level: "Balanced",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy aroma with subtle spice; compact buds",
    effects: "Calm, Focused, Euphoric",
    negatives: "dry mouth, dizziness",
    uses: "Suitable for medical use and stress relief",
    thc_rating: 3.5,
    user_rating: 3.75,
    combined_rating: 3.63
  },
  {
    name: "Canna-Tsu",
    overview: "Hybrid strain featuring balanced levels of THC and CBD for a mild, uplifting experience.",
    genetic_type: "Hybrid",
    lineage: "Cannatonic x Sour Tsunami",
    thc_range: "4-8%",
    cbd_level: "Balanced",
    dominant_terpenes: "Limonene, Pinene",
    qualitative_insights: "Subtle citrus aroma with herbal notes; light buds",
    effects: "Calm, Happy, Clear-headed",
    negatives: "dry mouth, fatigue",
    uses: "Used for mild pain and anxiety relief",
    thc_rating: 3.5,
    user_rating: 3.75,
    combined_rating: 3.63
  },
  {
    name: "ACDC",
    overview: "CBD-dominant strain with minimal psychoactive effects, prized for its therapeutic benefits.",
    genetic_type: "CBD-dominant",
    lineage: "Cannatonic phenotype",
    thc_range: "1-6%",
    cbd_level: "Very High",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Earthy, herbal aroma; non-resinous buds",
    effects: "Clear-headed, Relaxed, Focused",
    negatives: "none",
    uses: "Ideal for chronic pain, inflammation, anxiety",
    thc_rating: 1.5,
    user_rating: 1.75,
    combined_rating: 1.63
  },
  {
    name: "Ringo's Gift",
    overview: "Hybrid strain with high CBD offering a balanced and clear-headed experience.",
    genetic_type: "Hybrid",
    lineage: "Harle-Tsu x ACDC",
    thc_range: "Varies (1:1–24:1 ratio)",
    cbd_level: "High",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Mild, earthy aroma with sweet undertones; moderate buds",
    effects: "Calm, Focused, Relaxed",
    negatives: "dry mouth, sedation",
    uses: "Used for pain, anxiety, seizure management",
    thc_rating: 2,
    user_rating: 2.25,
    combined_rating: 2.13
  },
  {
    name: "Sour Tsunami",
    overview: "CBD-dominant strain known for its low THC content and effective pain relief properties.",
    genetic_type: "CBD-dominant",
    lineage: "Sour Diesel phenotype",
    thc_range: "6-10%",
    cbd_level: "High",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Tangy, diesel aroma with earthy notes; less resinous",
    effects: "Calm, Relaxed, Focused",
    negatives: "dry mouth, sedation",
    uses: "Ideal for chronic pain and inflammation",
    thc_rating: 1.5,
    user_rating: 1.75,
    combined_rating: 1.63
  },
  {
    name: "Harle-Tsu",
    overview: "Balanced CBD-rich hybrid offering mild euphoria with significant therapeutic benefits.",
    genetic_type: "Hybrid",
    lineage: "Harlequin x Canna-Tsu",
    thc_range: "4-10%",
    cbd_level: "High",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, herbal scent with subtle citrus; light buds",
    effects: "Clear-headed, Calm, Relaxed",
    negatives: "dry mouth, fatigue",
    uses: "Used for anxiety and pain relief",
    thc_rating: 2,
    user_rating: 2.25,
    combined_rating: 2.13
  },
  {
    name: "Blue Cheese",
    overview: "Indica-dominant hybrid with a pungent, cheese-like aroma and deeply relaxing effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Blueberry x UK Cheese",
    thc_range: "18-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Strong cheesy aroma with sweet berry undertones; dense buds",
    effects: "Relaxed, Euphoric, Sedated",
    negatives: "dry mouth, drowsiness",
    uses: "Great for stress relief and relaxation",
    thc_rating: 7.5,
    user_rating: 7.25,
    combined_rating: 7.38
  },
  {
    name: "Orange Bud",
    overview: "Sativa-dominant strain celebrated for its vibrant citrus flavor and uplifting effects.",
    genetic_type: "Sativa-dominant",
    lineage: "Afghani x Thai",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Bright citrus aroma with a hint of spice; light, airy buds",
    effects: "Energetic, Uplifted, Happy",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for daytime use and mood elevation",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "LA Confidential",
    overview: "Indica-dominant strain known for its smooth, pine and spice flavors and calming effects.",
    genetic_type: "Indica-dominant",
    lineage: "Afghani x OG Kush",
    thc_range: "16-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Earthy, pine aroma with subtle sweetness; resinous buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Used for stress relief and insomnia",
    thc_rating: 7,
    user_rating: 7,
    combined_rating: 7.00
  },
  {
    name: "God's Gift",
    overview: "Indica-dominant hybrid offering a powerful, euphoric high with a sweet, grape aroma.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Granddaddy Purple x OG Kush",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Rich, sweet grape aroma with sticky, dense buds",
    effects: "Relaxed, Euphoric, Sedated",
    negatives: "dry mouth, couch-lock",
    uses: "Ideal for pain relief and stress management",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "NYC Diesel",
    overview: "Sativa-dominant strain with a strong diesel aroma and uplifting, creative effects.",
    genetic_type: "Sativa-dominant",
    lineage: "Diesel x Unknown",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Pungent diesel scent with hints of citrus; frosty buds",
    effects: "Energized, Creative, Uplifted",
    negatives: "dry mouth, anxiety",
    uses: "Great for daytime creativity and focus",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Skunk #1",
    overview: "Classic hybrid known for its strong, skunky aroma and balanced, long-lasting effects.",
    genetic_type: "Hybrid",
    lineage: "Skunk #1 lineage",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Pungent, skunky odor with earthy undertones; sticky buds",
    effects: "Happy, Relaxed, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and mood elevation",
    thc_rating: 6.25,
    user_rating: 6,
    combined_rating: 6.13
  },
  {
    name: "Lemon Skunk",
    overview: "Hybrid strain offering a zesty lemon flavor and an energetic, uplifting high.",
    genetic_type: "Hybrid",
    lineage: "Skunk x Lemon Thai",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Bright lemon aroma with skunky undertones; light buds",
    effects: "Energized, Uplifted, Happy",
    negatives: "dry mouth, anxiety",
    uses: "Great for daytime use and creative tasks",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Master Kush",
    overview: "Indica-dominant strain renowned for its earthy, spicy flavor and deeply calming effects.",
    genetic_type: "Indica-dominant",
    lineage: "Afghani lineage",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Earthy, herbal aroma with a subtle spice; dense buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and pain management",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Hindu Kush",
    overview: "Pure indica known for its earthy, woody flavors and deeply relaxing effects.",
    genetic_type: "Indica (Pure)",
    lineage: "Hindu Kush Landrace",
    thc_range: "16-21%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Earthy, woody aroma with a hint of spice; compact buds",
    effects: "Calm, Relaxed, Sedated",
    negatives: "dry mouth, couch-lock",
    uses: "Used for relaxation and pain relief",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Afghani",
    overview: "Pure indica landrace with a strong, earthy aroma and heavy, sedative effects.",
    genetic_type: "Indica (Pure)",
    lineage: "Afghani Landrace",
    thc_range: "18-23%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, hash-like aroma; resinous, dense buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for pain relief and insomnia",
    thc_rating: 7.5,
    user_rating: 7.25,
    combined_rating: 7.38
  },
  {
    name: "Pakistani Chitral Kush",
    overview: "Robust pure indica with a distinct earthy and spicy flavor profile and potent effects.",
    genetic_type: "Indica (Pure)",
    lineage: "Pakistani Landrace",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Pinene",
    qualitative_insights: "Earthy, spicy aroma with resinous buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, couch-lock",
    uses: "Used for chronic pain and insomnia",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Blueberry Kush",
    overview: "Hybrid strain combining fruity blueberry flavors with classic Kush earthiness.",
    genetic_type: "Hybrid",
    lineage: "Blueberry x Kush",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Sweet blueberry aroma with earthy, herbal notes; dense buds",
    effects: "Relaxed, Happy, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and mood enhancement",
    thc_rating: 8,
    user_rating: 7.75,
    combined_rating: 7.88
  },
  {
    name: "Cherry OG",
    overview: "Hybrid strain known for its sweet cherry flavor and potent, balanced high.",
    genetic_type: "Hybrid",
    lineage: "Cherry Pie x OG Kush",
    thc_range: "20-26%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet cherry aroma with earthy undertones; sticky buds",
    effects: "Relaxed, Euphoric, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Used for stress relief and pain management",
    thc_rating: 9,
    user_rating: 8.75,
    combined_rating: 8.88
  },
  {
    name: "Jack Flash",
    overview: "Indica-dominant hybrid delivering a potent, sedative high with a spicy, herbal flavor.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Jack the Ripper x Flashback",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Herbal, spicy aroma with a hint of citrus; dense buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for nighttime use and pain relief",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "White Rhino",
    overview: "Indica-dominant strain known for its heavy, resinous buds and powerful body high.",
    genetic_type: "Indica-dominant",
    lineage: "Afghani x Unknown",
    thc_range: "18-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, pine aroma with a hint of sweetness; chunky buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, couch-lock",
    uses: "Used for severe pain and stress relief",
    thc_rating: 7.5,
    user_rating: 7.25,
    combined_rating: 7.38
  },
  {
    name: "Alien OG",
    overview: "Hybrid strain celebrated for its potent, spacey high and complex pine-citrus flavors.",
    genetic_type: "Hybrid",
    lineage: "Tahoe OG x Alien Kush",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Pine and citrus aroma with a touch of earthiness; frosty buds",
    effects: "Euphoric, Creative, Relaxed",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for creative sessions and relaxation",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Critical Jack",
    overview: "Hybrid that merges the uplifting effects of Jack Herer with the heavy yields of Critical Mass.",
    genetic_type: "Hybrid",
    lineage: "Jack Herer x Critical Mass",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Balanced aroma with hints of spice and earth; robust buds",
    effects: "Happy, Relaxed, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Great for stress relief and creative inspiration",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Agent Diesel",
    overview: "Hybrid strain with a robust diesel aroma and a balanced, energizing high.",
    genetic_type: "Hybrid",
    lineage: "Diesel x Unknown",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Strong diesel scent with citrus hints; resinous buds",
    effects: "Energized, Uplifted, Focused",
    negatives: "dry mouth, anxiety",
    uses: "Ideal for daytime focus and creativity",
    thc_rating: 8,
    user_rating: 7.75,
    combined_rating: 7.88
  },
  {
    name: "Candyland",
    overview: "Sativa-dominant hybrid offering a sweet, candy-like flavor with an uplifting high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Unknown (landrace blend)",
    thc_range: "16-22%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Sweet, sugary aroma; light, airy buds",
    effects: "Happy, Euphoric, Energetic",
    negatives: "dry mouth, dry eyes",
    uses: "Suitable for daytime energy and creativity",
    thc_rating: 7,
    user_rating: 7,
    combined_rating: 7.00
  },
  {
    name: "Tangie",
    overview: "Sativa-dominant strain famous for its strong citrus aroma and euphoric, uplifting effects.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Grapefruit x California Orange",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Vibrant citrus scent with sweet undertones; frosty buds",
    effects: "Uplifted, Energetic, Creative",
    negatives: "dry mouth, anxiety",
    uses: "Perfect for boosting mood and creativity",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Chernobyl",
    overview: "Hybrid strain with an earthy, pungent aroma and a balanced mix of cerebral and body effects.",
    genetic_type: "Hybrid",
    lineage: "Unknown (landrace blend)",
    thc_range: "16-20%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, spicy aroma; compact, dense buds",
    effects: "Balanced, Euphoric, Relaxed",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for daytime use and mild pain relief",
    thc_rating: 6.5,
    user_rating: 6.25,
    combined_rating: 6.38
  },
  {
    name: "LSD",
    overview: "Sativa-dominant hybrid renowned for its psychedelic, mind-bending high and complex flavor profile.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Unknown (Haze lineage)",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Terpinolene, Myrcene",
    qualitative_insights: "Psychedelic, earthy aroma with hints of citrus; trichome-rich buds",
    effects: "Creative, Euphoric, Uplifted",
    negatives: "dry mouth, paranoia",
    uses: "Great for creative exploration and social settings",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Romulan",
    overview: "Indica-dominant strain delivering a potent, sedative high with an earthy, pine flavor.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Indica landrace",
    thc_range: "20-26%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, pine aroma with spicy undertones; dense buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, couch-lock",
    uses: "Ideal for evening use and pain management",
    thc_rating: 9,
    user_rating: 8.75,
    combined_rating: 8.88
  },
  {
    name: "Berry White",
    overview: "Hybrid strain offering a sweet berry flavor with a balanced, uplifting high.",
    genetic_type: "Hybrid",
    lineage: "Unknown (landrace blend)",
    thc_range: "15-21%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet berry aroma with subtle earthy notes; light buds",
    effects: "Happy, Euphoric, Relaxed",
    negatives: "dry mouth, dry eyes",
    uses: "Great for mood elevation and relaxation",
    thc_rating: 6.5,
    user_rating: 6.25,
    combined_rating: 6.38
  },
  {
    name: "Blackberry Kush",
    overview: "Indica-dominant hybrid known for its rich, blackberry flavor and calming effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Unknown (Kush lineage)",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Sweet, berry aroma with earthy, herbal notes; compact buds",
    effects: "Relaxed, Sedated, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and insomnia",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Forbidden Berry",
    overview: "Hybrid strain combining sweet berry flavors with a potent, relaxing high.",
    genetic_type: "Hybrid",
    lineage: "Forbidden Fruit x Blackberry Kush",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Fruity, berry aroma with earthy undertones; resinous buds",
    effects: "Relaxed, Euphoric, Happy",
    negatives: "dry mouth, dry eyes",
    uses: "Suitable for evening relaxation and mood enhancement",
    thc_rating: 8,
    user_rating: 7.75,
    combined_rating: 7.88
  },
  {
    name: "Sour OG",
    overview: "Hybrid strain featuring a sour, pungent aroma with powerful, sedative effects.",
    genetic_type: "Hybrid",
    lineage: "OG Kush x Sour Diesel",
    thc_range: "20-26%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Sour, pungent aroma with earthy undertones; sticky buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, couch-lock",
    uses: "Great for pain relief and heavy relaxation",
    thc_rating: 9,
    user_rating: 8.5,
    combined_rating: 8.75
  },
  {
    name: "God Bud",
    overview: "Indica-dominant strain revered for its heavy, sedative high and earthy, herbal flavor.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Unknown (classic strain)",
    thc_range: "15-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Earthy, herbal aroma with a subtle sweetness; dense buds",
    effects: "Relaxed, Sedated, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for chronic pain and insomnia",
    thc_rating: 6.75,
    user_rating: 6.5,
    combined_rating: 6.63
  },
  {
    name: "Cheese",
    overview: "Indica-dominant hybrid noted for its pungent, cheesy aroma and balanced, relaxing effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "UK Cheese Landrace",
    thc_range: "18-22%",
    cbd_level: "Low",
    dominant_terpenes: "Caryophyllene, Myrcene",
    qualitative_insights: "Strong cheesy odor with earthy undertones; dense, sticky buds",
    effects: "Relaxed, Euphoric, Happy",
    negatives: "dry mouth, dry eyes",
    uses: "Perfect for stress relief and creative pursuits",
    thc_rating: 7.5,
    user_rating: 7.25,
    combined_rating: 7.38
  },
  {
    name: "G13",
    overview: "Potent hybrid with a mysterious lineage offering a powerful, euphoric high.",
    genetic_type: "Hybrid",
    lineage: "Urban legend strain",
    thc_range: "20-26%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Pungent, earthy aroma with hints of diesel; compact buds",
    effects: "Euphoric, Creative, Relaxed",
    negatives: "dry mouth, dizziness",
    uses: "Ideal for experienced users seeking strong effects",
    thc_rating: 9,
    user_rating: 8.75,
    combined_rating: 8.88
  },
  {
    name: "Blueberry OG",
    overview: "Hybrid strain merging the sweet flavors of Blueberry with the potency of OG Kush.",
    genetic_type: "Hybrid",
    lineage: "Blueberry x OG Kush",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Sweet blueberry aroma with earthy, pine undertones; resinous buds",
    effects: "Relaxed, Euphoric, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Great for relaxation and mood enhancement",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "Cherry Bomb",
    overview: "Hybrid strain with an explosive cherry flavor and a dynamic, balanced high.",
    genetic_type: "Hybrid",
    lineage: "Cherry Pie x Unknown",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Bold cherry aroma with a hint of spice; dense buds",
    effects: "Euphoric, Energetic, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for creative pursuits and social gatherings",
    thc_rating: 8,
    user_rating: 8,
    combined_rating: 8.00
  },
  {
    name: "Mango Kush",
    overview: "Indica-dominant hybrid offering a tropical mango flavor with deeply relaxing effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Afghani x Mango",
    thc_range: "20-26%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Tropical mango aroma with earthy undertones; dense, resinous buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Used for stress relief and relaxation",
    thc_rating: 9,
    user_rating: 8.75,
    combined_rating: 8.88
  },
  {
    name: "Pineapple Chunk",
    overview: "Indica-dominant hybrid featuring a sweet pineapple aroma and a heavy, sedative high.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Pineapple x Chunk",
    thc_range: "16-23%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Tropical pineapple scent with earthy notes; chunky buds",
    effects: "Relaxed, Sedated, Happy",
    negatives: "dry mouth, couch-lock",
    uses: "Ideal for evening use and pain management",
    thc_rating: 7.25,
    user_rating: 7,
    combined_rating: 7.13
  },
  {
    name: "Jillybean",
    overview: "Hybrid strain known for its fruity, floral flavor and uplifting, creative effects.",
    genetic_type: "Hybrid",
    lineage: "Unknown (landrace blend)",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Fruity, floral aroma with a sweet finish; light buds",
    effects: "Uplifted, Euphoric, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Great for daytime use and creative inspiration",
    thc_rating: 6.25,
    user_rating: 6,
    combined_rating: 6.13
  },
  {
    name: "Strawberry Banana",
    overview: "Hybrid strain combining sweet strawberry and banana flavors with a balanced high.",
    genetic_type: "Hybrid",
    lineage: "Unknown (blend)",
    thc_range: "18-26%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Myrcene",
    qualitative_insights: "Sweet, tropical aroma with a creamy finish; resinous buds",
    effects: "Happy, Relaxed, Euphoric",
    negatives: "dry mouth, dizziness",
    uses: "Ideal for mood elevation and relaxation",
    thc_rating: 8.5,
    user_rating: 8.25,
    combined_rating: 8.38
  },
  {
    name: "Tropicana Cookies",
    overview: "Sativa-dominant hybrid delivering a burst of citrus and cookie flavors with an energetic high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Cookie genetics x Tangie",
    thc_range: "20-28%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Zesty citrus aroma with a sweet, baked undertone; frosty buds",
    effects: "Energized, Uplifted, Creative",
    negatives: "dry mouth, dry eyes",
    uses: "Perfect for daytime creativity and social events",
    thc_rating: 9.5,
    user_rating: 9,
    combined_rating: 9.25
  },
  {
    name: "UK Cheese",
    overview: "Indica-dominant variant of Cheese known for its pungent aroma and relaxing, euphoric effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "UK Landrace",
    thc_range: "15-20%",
    cbd_level: "Low",
    dominant_terpenes: "Caryophyllene, Myrcene",
    qualitative_insights: "Strong cheesy odor with herbal undertones; sticky buds",
    effects: "Relaxed, Euphoric, Happy",
    negatives: "dry mouth, dry eyes",
    uses: "Great for stress relief and relaxation",
    thc_rating: 6.25,
    user_rating: 6,
    combined_rating: 6.13
  },
  {
    name: "Raspberry Kush",
    overview: "Indica-dominant hybrid with a sweet raspberry flavor and a deeply calming high.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Afghani x Unknown",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Sweet raspberry aroma with earthy notes; dense buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for evening use and pain relief",
    thc_rating: 8,
    user_rating: 7.75,
    combined_rating: 7.88
  },
  {
    name: "Orange Cookies",
    overview: "Hybrid strain combining citrus and sweet cookie flavors with a balanced, uplifting high.",
    genetic_type: "Hybrid",
    lineage: "Girl Scout Cookies x Orange Velvet",
    thc_range: "18-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Citrus-infused aroma with sweet undertones; resinous buds",
    effects: "Happy, Relaxed, Uplifted",
    negatives: "dry mouth, dry eyes",
    uses: "Suitable for mood enhancement and stress relief",
    thc_rating: 8.25,
    user_rating: 8,
    combined_rating: 8.13
  },
  {
    name: "White Tahoe Cookies",
    overview: "Indica-dominant hybrid featuring a sweet, citrusy flavor and potent, relaxing effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "Tahoe OG x Cookies",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Sweet citrus aroma with earthy hints; dense, sticky buds",
    effects: "Relaxed, Euphoric, Sedated",
    negatives: "dry mouth, couch-lock",
    uses: "Ideal for evening relaxation and pain management",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Fire OG",
    overview: "Indica-dominant strain known for its intense, spicy pine flavor and powerful sedative effects.",
    genetic_type: "Indica-dominant Hybrid",
    lineage: "OG Kush lineage",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Spicy, pine aroma with a hint of earthiness; chunky buds",
    effects: "Relaxed, Sedated, Euphoric",
    negatives: "dry mouth, drowsiness",
    uses: "Used for severe pain relief and stress reduction",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Headband",
    overview: "Hybrid strain recognized for its tight, band-like effect and a balanced cerebral and body high.",
    genetic_type: "Hybrid",
    lineage: "Super Silver Haze x OG Kush",
    thc_range: "18-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Subtle, earthy aroma with hints of diesel; compact buds",
    effects: "Euphoric, Relaxed, Focused",
    negatives: "dry mouth, fatigue",
    uses: "Great for migraine relief and creative focus",
    thc_rating: 7.5,
    user_rating: 7.25,
    combined_rating: 7.38
  },
  {
    name: "Jack the Ripper",
    overview: "Potent hybrid with a sharp, spicy flavor and a fast-acting, cerebral high.",
    genetic_type: "Hybrid",
    lineage: "Jack Herer x Unknown",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Spicy, herbal aroma with a hint of citrus; dense buds",
    effects: "Euphoric, Creative, Energetic",
    negatives: "dry mouth, dry eyes",
    uses: "Ideal for creative inspiration and stress relief",
    thc_rating: 8,
    user_rating: 8,
    combined_rating: 8.00
  },
  {
    name: "Cinderella 99",
    overview: "Sativa-dominant hybrid known for its uplifting, energetic high and sweet, citrus flavor.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Unknown (landrace blend)",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Sweet citrus aroma with floral hints; airy buds",
    effects: "Energized, Uplifted, Creative",
    negatives: "dry mouth, anxiety",
    uses: "Great for daytime energy and creativity",
    thc_rating: 8,
    user_rating: 8.25,
    combined_rating: 8.13
  },
  {
    name: "Blue Cookies",
    overview: "Hybrid strain combining sweet blueberry flavors with a calming, balanced high.",
    genetic_type: "Hybrid",
    lineage: "Blueberry x Girl Scout Cookies",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Caryophyllene",
    qualitative_insights: "Sweet blueberry aroma with earthy undertones; resinous buds",
    effects: "Relaxed, Euphoric, Happy",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for relaxation and mood enhancement",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "Mimosa",
    overview: "Sativa-dominant hybrid offering a vibrant citrus and sweet, tangy flavor with an uplifting high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Citrus x Purple Punch",
    thc_range: "20-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Bright citrus aroma with sweet, fruity notes; light buds",
    effects: "Energized, Uplifted, Happy",
    negatives: "dry mouth, dry eyes",
    uses: "Perfect for daytime use and social gatherings",
    thc_rating: 8.75,
    user_rating: 8.5,
    combined_rating: 8.63
  },
  {
    name: "LA Kush",
    overview: "Hybrid strain known for its spicy, earthy flavor and balanced, calming effects.",
    genetic_type: "Hybrid",
    lineage: "LA x Kush lineage",
    thc_range: "17-22%",
    cbd_level: "Low",
    dominant_terpenes: "Myrcene, Limonene",
    qualitative_insights: "Earthy, spicy aroma with subtle floral hints; moderate buds",
    effects: "Relaxed, Euphoric, Focused",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for stress relief and relaxation",
    thc_rating: 7.25,
    user_rating: 7,
    combined_rating: 7.13
  },
  {
    name: "Amnesia Lemon",
    overview: "Sativa-dominant hybrid blending citrus and earthy flavors for an energizing, creative high.",
    genetic_type: "Sativa-dominant Hybrid",
    lineage: "Amnesia x Lemon Skunk",
    thc_range: "18-24%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Terpinolene",
    qualitative_insights: "Bright lemon aroma with earthy undertones; light, airy buds",
    effects: "Energized, Uplifted, Creative",
    negatives: "dry mouth, anxiety",
    uses: "Great for daytime creativity and mood boost",
    thc_rating: 8,
    user_rating: 8,
    combined_rating: 8.00
  },
  {
    name: "Forbidden Jack",
    overview: "Hybrid strain merging tropical fruit notes with a potent, balanced high for a unique experience.",
    genetic_type: "Hybrid",
    lineage: "Forbidden Fruit x Jack Herer",
    thc_range: "19-25%",
    cbd_level: "Low",
    dominant_terpenes: "Limonene, Caryophyllene",
    qualitative_insights: "Tropical, fruity aroma with spicy hints; resinous buds",
    effects: "Euphoric, Relaxed, Creative",
    negatives: "dry mouth, drowsiness",
    uses: "Ideal for creative sessions and stress relief",
    thc_rating: 8.5,
    user_rating: 8.25,
    combined_rating: 8.38
  }
];



// Achievement icon mapping
export const ACHIEVEMENT_ICONS = {
  "Daily & Weekly Streaks": "calendar-check",
  "Moderation & Goal-Oriented": "target",
  "Strain Exploration": "cannabis",
  "Medical-Focused": "medical-bag",
  "Recreational-Focused": "party-popper",
  "AI Interaction": "robot",
  "Mood & Journaling": "notebook",
  "Referral & Community": "account-group",
  "Morning/Evening Check-Ins": "clock-time-eight",
  "Long-Term Milestones": "trophy",
  "Themed Celebrations": "balloon"
};

// Achievement action types - for checking which achievements to evaluate
export const ACHIEVEMENT_ACTION_TYPES = {
  LOG_CONSUMPTION: "log_consumption",
  LOG_MOOD: "log_mood",
  LOG_STRAIN: "log_strain",
  CONNECT_DEVICE: "connect_device",
  USE_AI: "use_ai",
  COMPLETE_PROFILE: "complete_profile",
  REFER_FRIEND: "refer_friend",
  SET_GOAL: "set_goal",
  MEET_GOAL: "meet_goal",
  REDUCE_USAGE: "reduce_usage",
  TRACK_SYMPTOMS: "track_symptoms",
  TRACK_MORNING: "track_morning",
  TRACK_EVENING: "track_evening",
  CHECK_DATE: "check_date" // For themed celebrations
  // Add more action types as needed
};

// Achievement data - all 73 achievements from the CSV
export const ACHIEVEMENTS = [
  {
    id: 1,
    category: "Daily & Weekly Streaks",
    name: "First Step",
    unlockCondition: "Log consumption or a mood entry for the first time",
    notes: "Encourages that very first act of mindfulness.",
    icon: "foot-print",
    complexity: 1
  },
  {
    id: 2,
    category: "Daily & Weekly Streaks",
    name: "Trak+ Kickoff",
    unlockCondition: "Record your first automatically tracked session with the Trak+ device",
    notes: "Spotlights using the Trak+ for automated hit tracking.",
    icon: "devices",
    complexity: 1
  },
  {
    id: 3,
    category: "Daily & Weekly Streaks",
    name: "3-Day Dynamo",
    unlockCondition: "Log usage for 3 consecutive days",
    notes: "Builds early momentum and routine.",
    icon: "calendar-check",
    complexity: 2
  },
  {
    id: 4,
    category: "Daily & Weekly Streaks",
    name: "7-Day Steady & Ready",
    unlockCondition: "Log usage for 7 consecutive days",
    notes: "Reinforces a weekly habit; awards small Strain Points perk.",
    icon: "calendar-check",
    complexity: 2
  },
  {
    id: 5,
    category: "Daily & Weekly Streaks",
    name: "14-Day Consistency King/Queen",
    unlockCondition: "Log usage for 14 consecutive days",
    notes: "Begins forming a lasting habit.",
    icon: "calendar-check-outline",
    complexity: 3
  },
  {
    id: 6,
    category: "Daily & Weekly Streaks",
    name: "28-Day Wellness Warrior",
    unlockCondition: "Log usage for 28 consecutive days (4 weeks)",
    notes: "Promotes a longer-term streak.",
    icon: "calendar-month",
    complexity: 4
  },
  {
    id: 7,
    category: "Daily & Weekly Streaks",
    name: "60-Day Dedicated Drifter",
    unlockCondition: "Log usage for 60 consecutive days",
    notes: "Shows commitment to mindful tracking.",
    icon: "calendar-multiple-check",
    complexity: 5
  },
  {
    id: 8,
    category: "Daily & Weekly Streaks",
    name: "90-Day Canna Champion",
    unlockCondition: "Log usage for 90 consecutive days",
    notes: "Could unlock a special emblem or color theme.",
    icon: "calendar-star",
    complexity: 5
  },
  {
    id: 9,
    category: "Daily & Weekly Streaks",
    name: "6-Month Mastery",
    unlockCondition: "Log usage for 6 consecutive months",
    notes: "Rewards deep long-term engagement.",
    icon: "calendar-clock",
    complexity: 6
  },
  {
    id: 10,
    category: "Daily & Weekly Streaks",
    name: "21-Day Green Groove",
    unlockCondition: "Log daily for 21 consecutive days",
    notes: "Establishes a healthy, consistent rhythm.",
    icon: "calendar-cursor",
    complexity: 4
  },
  {
    id: 11,
    category: "Daily & Weekly Streaks",
    name: "45-Day Flow Finder",
    unlockCondition: "Log daily for 45 consecutive days",
    notes: "Reinforces a mid-range streak milestone.",
    icon: "calendar-refresh",
    complexity: 5
  },
  {
    id: 12,
    category: "Daily & Weekly Streaks",
    name: "365-Day Beacon",
    unlockCondition: "Log at least once per week for a full year",
    notes: "Symbolizes ultimate consistency and dedication.",
    icon: "calendar-heart",
    complexity: 7
  },
  {
    id: 13,
    category: "Moderation & Goal-Oriented",
    name: "Goal Getter",
    unlockCondition: "Set a daily usage goal and meet it 3 days in a row",
    notes: "Celebrates short-term consistency.",
    icon: "bullseye-arrow",
    complexity: 2
  },
  {
    id: 14,
    category: "Moderation & Goal-Oriented",
    name: "Sensible Step-Down",
    unlockCondition: "Reduce weekly consumption by 10% compared to prior week",
    notes: "Rewards healthy moderation.",
    icon: "trending-down",
    complexity: 3
  },
  {
    id: 15,
    category: "Moderation & Goal-Oriented",
    name: "Progress Personified",
    unlockCondition: "Reduce monthly consumption by 15%+",
    notes: "Highlights significant self-control.",
    icon: "chart-line-variant",
    complexity: 4
  },
  {
    id: 16,
    category: "Moderation & Goal-Oriented",
    name: "Steady As You Go",
    unlockCondition: "Meet exact daily goal 5 days in a row",
    notes: "Proves adherence to precise limits.",
    icon: "target-account",
    complexity: 3
  },
  {
    id: 17,
    category: "Moderation & Goal-Oriented",
    name: "Balanced Breakthrough",
    unlockCondition: "At least 1 day each week below your daily goal for a month",
    notes: "Rewards small, consistent improvements.",
    icon: "scale-balance",
    complexity: 4
  },
  {
    id: 18,
    category: "Moderation & Goal-Oriented",
    name: "Cutback Crusader",
    unlockCondition: "Lower usage (by any set %/target) for 3 consecutive weeks",
    notes: "Empowers gradual reduction to avoid chaos.",
    icon: "chart-timeline-variant-shimmer",
    complexity: 5
  },
  {
    id: 19,
    category: "Moderation & Goal-Oriented",
    name: "Pace Maker",
    unlockCondition: "Set a weekly usage limit and meet it for a full month",
    notes: "Encourages steady, well-paced approach.",
    icon: "speedometer",
    complexity: 4
  },
  {
    id: 20,
    category: "Strain Exploration",
    name: "Strain Explorer",
    unlockCondition: "Log 3+ different strains in a single week",
    notes: "Promotes variety and learning.",
    icon: "compass",
    complexity: 2
  },
  {
    id: 21,
    category: "Strain Exploration",
    name: "Sativa Superstar",
    unlockCondition: "Log at least one Sativa strain daily for 7 days",
    notes: "Fun nod to uplifting strain fans.",
    icon: "leaf",
    complexity: 3
  },
  {
    id: 22,
    category: "Strain Exploration",
    name: "Indica Innovator",
    unlockCondition: "Log at least one Indica strain daily for 7 days",
    notes: "Highlights the calmer side of cannabis.",
    icon: "moon-waning-crescent",
    complexity: 3
  },
  {
    id: 23,
    category: "Strain Exploration",
    name: "Hybrid Hero",
    unlockCondition: "Log a Hybrid strain daily for 7 days",
    notes: "Celebrates a balanced approach.",
    icon: "yin-yang",
    complexity: 3
  },
  {
    id: 24,
    category: "Strain Exploration",
    name: "Flavors of the Field",
    unlockCondition: "Log 10+ unique strains overall",
    notes: "Encourages exploration and record-keeping.",
    icon: "cannabis",
    complexity: 3
  },
  {
    id: 25,
    category: "Strain Exploration",
    name: "Canna Connoisseur",
    unlockCondition: "Log 20+ unique strains overall",
    notes: "Shows next-level variety expertise.",
    icon: "flower",
    complexity: 4
  },
  {
    id: 26,
    category: "Strain Exploration",
    name: "One-Strain Wonder",
    unlockCondition: "Use the same strain for 7 consecutive days",
    notes: "Helps understand a single strain's effects.",
    icon: "repeat",
    complexity: 2
  },
  {
    id: 27,
    category: "Strain Exploration",
    name: "Flavors of the World",
    unlockCondition: "Log 30+ unique strains overall",
    notes: "Prestige tier for deep strain exploration.",
    icon: "earth",
    complexity: 5
  },
  {
    id: 28,
    category: "Strain Exploration",
    name: "Terpene Tourist",
    unlockCondition: "Log 5 strains with distinctly different terpene profiles",
    notes: "Encourages knowledge beyond THC/CBD.",
    icon: "molecule",
    complexity: 4
  },
  {
    id: 29,
    category: "Strain Exploration",
    name: "Flavor Flight",
    unlockCondition: "Sample 5 new strains in one calendar month",
    notes: "Suggests a curated 'tasting experience.'",
    icon: "palette",
    complexity: 3
  },
  {
    id: 30,
    category: "Strain Exploration",
    name: "Signature Strain",
    unlockCondition: "Use the same strain for 14 days, tracking detailed effects",
    notes: "Promotes in-depth familiarity with a favorite.",
    icon: "fingerprint",
    complexity: 4
  },
  {
    id: 31,
    category: "Medical-Focused",
    name: "Pain Progress",
    unlockCondition: "Log pain levels before/after consumption for 7 sessions with relief",
    notes: "Encourages data-driven symptom tracking.",
    icon: "bandage",
    complexity: 3
  },
  {
    id: 32,
    category: "Medical-Focused",
    name: "Stress Smasher",
    unlockCondition: "Log consumption for stress relief at least 5 times in 1 week with improvement",
    notes: "Promotes responsible stress management.",
    icon: "emoticon-cool",
    complexity: 3
  },
  {
    id: 33,
    category: "Medical-Focused",
    name: "Sleep Savior",
    unlockCondition: "Use for insomnia or better sleep 5 nights in a row with improved sleep rating",
    notes: "Supports healthy bedtime routines.",
    icon: "sleep",
    complexity: 3
  },
  {
    id: 34,
    category: "Medical-Focused",
    name: "Symptom Tracker",
    unlockCondition: "Log symptom severity daily for 14 consecutive days",
    notes: "Encourages thorough journaling of conditions.",
    icon: "chart-line",
    complexity: 4
  },
  {
    id: 35,
    category: "Medical-Focused",
    name: "Chronic Champion",
    unlockCondition: "Maintain usage log for a chronic condition over 30 days with reported improvement",
    notes: "Celebrates consistent, mindful medical use.",
    icon: "medical-bag",
    complexity: 5
  },
  {
    id: 36,
    category: "Medical-Focused",
    name: "Relief & Release",
    unlockCondition: "Show a 2-3 point drop in symptom severity for 3 consecutive sessions",
    notes: "Reinforces ongoing tracking and improvement.",
    icon: "arrow-down-bold-circle",
    complexity: 3
  },
  {
    id: 37,
    category: "Medical-Focused",
    name: "Guided Goals",
    unlockCondition: "Follow a specific medical usage plan for 2 weeks",
    notes: "Encourages alignment with personal health objectives.",
    icon: "clipboard-check",
    complexity: 4
  },
  {
    id: 38,
    category: "Medical-Focused",
    name: "Prescription Partner",
    unlockCondition: "Adhere to provider's recommended usage for 10 sessions, note improvement",
    notes: "Supports medically guided cannabis plans.",
    icon: "prescription",
    complexity: 4
  },
  {
    id: 39,
    category: "Recreational-Focused",
    name: "Weekend Wind-Down",
    unlockCondition: "Log usage on Fri/Sat/Sun specifically for leisure/relaxation",
    notes: "Encourages a mindful approach to weekend fun.",
    icon: "weekend",
    complexity: 2
  },
  {
    id: 40,
    category: "Recreational-Focused",
    name: "Creative Spark",
    unlockCondition: "Log a session that boosted creativity at least 3 times",
    notes: "Fosters purposeful, creative use.",
    icon: "lightbulb-on",
    complexity: 2
  },
  {
    id: 41,
    category: "Recreational-Focused",
    name: "Taste Tester",
    unlockCondition: "Log 5 different strains in a month purely for personal preference",
    notes: "Promotes mindful flavor exploration.",
    icon: "silverware-fork-knife",
    complexity: 3
  },
  {
    id: 42,
    category: "Recreational-Focused",
    name: "Chilled Out Champ",
    unlockCondition: "Log usage for relaxation 5 times in 14 days with mood notes",
    notes: "Rewards fun yet moderate consumption.",
    icon: "sofa",
    complexity: 2
  },
  {
    id: 43,
    category: "Recreational-Focused",
    name: "Social Session",
    unlockCondition: "Mark a session as social/friend-related once a week for 3 weeks",
    notes: "Highlights community aspect in a responsible way.",
    icon: "account-group",
    complexity: 2
  },
  {
    id: 44,
    category: "Recreational-Focused",
    name: "Social Spark",
    unlockCondition: "Log group sessions with improved/shared mood at least 3 times/month",
    notes: "Encourages healthy social enjoyment.",
    icon: "party-popper",
    complexity: 3
  },
  {
    id: 45,
    category: "Recreational-Focused",
    name: "Weekend Warrior",
    unlockCondition: "Log weekend sessions for 4 straight weekends without exceeding personal goals",
    notes: "Proves moderation during leisure times.",
    icon: "shield-outline",
    complexity: 3
  },
  {
    id: 46,
    category: "AI Interaction",
    name: "AI Curious",
    unlockCondition: "Use the AI feature for a personalized suggestion once",
    notes: "Introduces users to advanced app capabilities.",
    icon: "brain",
    complexity: 1
  },
  {
    id: 47,
    category: "AI Interaction",
    name: "AI Explorer",
    unlockCondition: "Follow AI-recommended strains/tips 5 times",
    notes: "Deepens engagement with app's AI resources.",
    icon: "robot",
    complexity: 2
  },
  {
    id: 48,
    category: "AI Interaction",
    name: "Digital Dilemma",
    unlockCondition: "Ask the AI about a symptom or mood goal, log before/after results",
    notes: "Highlights how AI can guide decision-making.",
    icon: "head-question",
    complexity: 2
  },
  {
    id: 49,
    category: "AI Interaction",
    name: "Feedback Fan",
    unlockCondition: "Provide feedback on AI-recommended outcomes at least 3 times",
    notes: "Helps refine AI suggestions; awards extra Strain Points.",
    icon: "message-reply-text",
    complexity: 2
  },
  {
    id: 50,
    category: "Mood & Journaling",
    name: "Mood Logger",
    unlockCondition: "Log your mood (before or after) daily for 7 days",
    notes: "Fosters consistent self-awareness.",
    icon: "emoticon",
    complexity: 2
  },
  {
    id: 51,
    category: "Mood & Journaling",
    name: "Diary Devotee",
    unlockCondition: "Log mood/experience 14 consecutive days",
    notes: "Encourages mindful reflection.",
    icon: "notebook",
    complexity: 3
  },
  {
    id: 52,
    category: "Mood & Journaling",
    name: "Emotional Explorer",
    unlockCondition: "Try 3 different strains and log how each affected your mood",
    notes: "Prompts curiosity about varied experiences.",
    icon: "emoticon-happy",
    complexity: 2
  },
  {
    id: 53,
    category: "Mood & Journaling",
    name: "Mind–Body Balance",
    unlockCondition: "Log a mood/symptom entry with every session for a full week",
    notes: "Promotes deeper introspection and tracking.",
    icon: "scale-balance",
    complexity: 3
  },
  {
    id: 54,
    category: "Referral & Community",
    name: "Spreading the Love",
    unlockCondition: "Refer 1 friend who signs up",
    notes: "Simple step into community-building.",
    icon: "account-plus",
    complexity: 1
  },
  {
    id: 55,
    category: "Referral & Community",
    name: "Community Builder",
    unlockCondition: "Refer 3 friends who sign up",
    notes: "Could award additional Strain Points or discount code.",
    icon: "account-multiple-plus",
    complexity: 2
  },
  {
    id: 56,
    category: "Referral & Community",
    name: "Trend Setter",
    unlockCondition: "Refer 5+ friends who sign up",
    notes: "Early evangelists help grow the user base.",
    icon: "trending-up",
    complexity: 3
  },
  {
    id: 57,
    category: "Referral & Community",
    name: "Grassroots Guru",
    unlockCondition: "Refer 10 friends who each log at least once",
    notes: "'Grassroots' nod to building a larger network.",
    icon: "sprout",
    complexity: 5
  },
  {
    id: 58,
    category: "Referral & Community",
    name: "App Ambassador",
    unlockCondition: "Share app achievements or invites that lead to sign-ups (3+ conversions)",
    notes: "Encourages gentle advocacy without pushing consumption.",
    icon: "medal",
    complexity: 3
  },
  {
    id: 59,
    category: "Morning/Evening Check-Ins",
    name: "Morning Mindfulness",
    unlockCondition: "Log a morning check-in for 7 consecutive days",
    notes: "Helps track how you feel starting each day.",
    icon: "weather-sunset-up",
    complexity: 2
  },
  {
    id: 60,
    category: "Morning/Evening Check-Ins",
    name: "Evening Wind-Down",
    unlockCondition: "Log an evening reflection for 7 consecutive days",
    notes: "Promotes intentional wind-down routines.",
    icon: "weather-sunset-down",
    complexity: 2
  },
  {
    id: 61,
    category: "Morning/Evening Check-Ins",
    name: "Full Day Focus",
    unlockCondition: "Log morning, midday, and evening for 7 consecutive days",
    notes: "Encourages holistic daily awareness.",
    icon: "clock-time-three",
    complexity: 4
  },
  {
    id: 62,
    category: "Long-Term Milestones",
    name: "100 Logs & Counting",
    unlockCondition: "Reach 100 total logged sessions",
    notes: "Marks a substantial data-driven milestone.",
    icon: "counter",
    complexity: 3
  },
  {
    id: 63,
    category: "Long-Term Milestones",
    name: "200 Logs & Counting",
    unlockCondition: "Reach 200 total logged sessions",
    notes: "Shows extended commitment.",
    icon: "numeric-2-circle",
    complexity: 4
  },
  {
    id: 64,
    category: "Long-Term Milestones",
    name: "500 Logs & Counting",
    unlockCondition: "Reach 500 total logged sessions",
    notes: "Could unlock a special theme or discount.",
    icon: "numeric-5-circle",
    complexity: 5
  },
  {
    id: 65,
    category: "Long-Term Milestones",
    name: "Year-Long Legend",
    unlockCondition: "Log usage at least weekly for a full year",
    notes: "Demonstrates mindful tracking over time.",
    icon: "calendar-text",
    complexity: 6
  },
  {
    id: 66,
    category: "Long-Term Milestones",
    name: "Dose Discovery",
    unlockCondition: "Log dosage consistently for 30 days to find personal 'sweet spot'",
    notes: "Promotes balanced consumption habits.",
    icon: "magnify-plus",
    complexity: 4
  },
  {
    id: 67,
    category: "Long-Term Milestones",
    name: "Personal Best",
    unlockCondition: "Achieve a self-set improvement goal (e.g., -20% usage)",
    notes: "Celebrates user-defined success.",
    icon: "star-circle",
    complexity: 3
  },
  {
    id: 68,
    category: "Long-Term Milestones",
    name: "750 Logs & Learning",
    unlockCondition: "Reach 750 total logged sessions",
    notes: "Highlights the insights gained from thorough tracking.",
    icon: "numeric-7-circle",
    complexity: 6
  },
  {
    id: 69,
    category: "Long-Term Milestones",
    name: "1K Commitment",
    unlockCondition: "Surpass 1,000 total logged sessions",
    notes: "Major testament to consistent usage (not higher consumption).",
    icon: "numeric-10-circle",
    complexity: 7
  },
  {
    id: 70,
    category: "Long-Term Milestones",
    name: "Multi-Year Marvel",
    unlockCondition: "Use the app for 2+ years (≥1 log/week or month)",
    notes: "Celebrates ultimate loyalty and mindful engagement.",
    icon: "cake-variant",
    complexity: 7
  },
  {
    id: 71,
    category: "Themed Celebrations",
    name: "Earth Day Eco-Toker",
    unlockCondition: "Log a session on Earth Day with an eco-friendly note or reflection",
    notes: "Encourages environmental consciousness with cannabis use.",
    icon: "earth",
    complexity: 2
  },
  {
    id: 72,
    category: "Themed Celebrations",
    name: "Harvest Hero",
    unlockCondition: "Log a session during autumn harvest season/fall equinox",
    notes: "Seasonal nod to mindful consumption and gratitude.",
    icon: "leaf-maple",
    complexity: 2
  },
  {
    id: 73,
    category: "Themed Celebrations",
    name: "4/20 Festive",
    unlockCondition: "Log on 4/20 while staying within personal goals/limits",
    notes: "Promotes responsible celebration of this cultural day.",
    icon: "calendar-star",
    complexity: 2
  }
];

// Progress calculation functions for different achievement types
export const ACHIEVEMENT_TRIGGERS = {
  // Daily & Weekly Streaks
  1: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  2: [ACHIEVEMENT_ACTION_TYPES.CONNECT_DEVICE],
  3: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  4: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  5: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  6: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  7: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  8: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  9: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  10: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  11: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  12: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  
  // Moderation & Goal-Oriented
  13: [ACHIEVEMENT_ACTION_TYPES.SET_GOAL, ACHIEVEMENT_ACTION_TYPES.MEET_GOAL],
  14: [ACHIEVEMENT_ACTION_TYPES.REDUCE_USAGE],
  15: [ACHIEVEMENT_ACTION_TYPES.REDUCE_USAGE],
  16: [ACHIEVEMENT_ACTION_TYPES.MEET_GOAL],
  17: [ACHIEVEMENT_ACTION_TYPES.MEET_GOAL],
  18: [ACHIEVEMENT_ACTION_TYPES.REDUCE_USAGE],
  19: [ACHIEVEMENT_ACTION_TYPES.SET_GOAL, ACHIEVEMENT_ACTION_TYPES.MEET_GOAL],
  
  // Strain Exploration
  20: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  21: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  22: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  23: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  24: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  25: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  26: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  27: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  28: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  29: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  30: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  
  // Medical-Focused
  31: [ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  32: [ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  33: [ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  34: [ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS],
  35: [ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  36: [ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS],
  37: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION, ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS],
  38: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION, ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS],
  
  // Recreational-Focused
  39: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  40: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  41: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN],
  42: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  43: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  44: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  45: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION, ACHIEVEMENT_ACTION_TYPES.MEET_GOAL],
  
  // AI Interaction
  46: [ACHIEVEMENT_ACTION_TYPES.USE_AI],
  47: [ACHIEVEMENT_ACTION_TYPES.USE_AI],
  48: [ACHIEVEMENT_ACTION_TYPES.USE_AI, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  49: [ACHIEVEMENT_ACTION_TYPES.USE_AI],
  
  // Mood & Journaling
  50: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  51: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  52: [ACHIEVEMENT_ACTION_TYPES.LOG_STRAIN, ACHIEVEMENT_ACTION_TYPES.LOG_MOOD],
  53: [ACHIEVEMENT_ACTION_TYPES.LOG_MOOD, ACHIEVEMENT_ACTION_TYPES.TRACK_SYMPTOMS, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  
  // Referral & Community
  54: [ACHIEVEMENT_ACTION_TYPES.REFER_FRIEND],
  55: [ACHIEVEMENT_ACTION_TYPES.REFER_FRIEND],
  56: [ACHIEVEMENT_ACTION_TYPES.REFER_FRIEND],
  57: [ACHIEVEMENT_ACTION_TYPES.REFER_FRIEND],
  58: [ACHIEVEMENT_ACTION_TYPES.REFER_FRIEND],
  
  // Morning/Evening Check-Ins
  59: [ACHIEVEMENT_ACTION_TYPES.TRACK_MORNING],
  60: [ACHIEVEMENT_ACTION_TYPES.TRACK_EVENING],
  61: [ACHIEVEMENT_ACTION_TYPES.TRACK_MORNING, ACHIEVEMENT_ACTION_TYPES.TRACK_EVENING, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  
  // Long-Term Milestones
  62: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  63: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  64: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  65: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  66: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  67: [ACHIEVEMENT_ACTION_TYPES.REDUCE_USAGE, ACHIEVEMENT_ACTION_TYPES.MEET_GOAL],
  68: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  69: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  70: [ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  
  // Themed Celebrations
  71: [ACHIEVEMENT_ACTION_TYPES.CHECK_DATE, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  72: [ACHIEVEMENT_ACTION_TYPES.CHECK_DATE, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION],
  73: [ACHIEVEMENT_ACTION_TYPES.CHECK_DATE, ACHIEVEMENT_ACTION_TYPES.LOG_CONSUMPTION]
};